name: Java CI with Maven
on:
  pull_request:
    branches: [ master ]
    
  workflow_dispatch:

jobs:
  maven-test:
    runs-on: ubuntu-latest
    name: Run tests with maven and selenium

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
        
    - name: Test with Maven
      run: mvn clean test
      
    - name: Test report
      uses: ScaCap/action-surefire-report@v1.0.5
      with:
        check_name: Maven Test Summary Report
        github_token: ${{ github.token }}
        report_paths: "target/surefire-reports/TEST-*.xml"
        
    - name: JUnit Report
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: JUnit Test Report
        path: build/test-results/test/TEST-*.xml
        reporter: java-junit
        fail-on-error: 'false'
        
    - name: Get Allure history
      uses: actions/checkout@v2
      if: always()
      continue-on-error: true
      with:
        ref: gh-pages
        path: gh-pages
        
    - name: Allure report
      uses: simple-elf/allure-report-action@master
      if: always()
      id: allure-report
      with:
        allure_results: allure-results
        allure_history: allure-history

    - name: Deploy allure report to Github Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v2
      env:
        PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: allure-history
